### ISSUE TITLE
for文の使い方

### ISSUE THREAD

**Issue by MikamiSyota** [c0a2109372/ProjExD#3]
https://github.com/c0a2109372/ProjExD/blob/3fc4596cc3c6594199442e96f616df556c32e183/ex02/calc.py#L47-L88
個人的には丁寧なコード進行でいいとおもいます。ですが、for文を1つにできるのではないかと思いました。計算機のボタンの数は多くても30個だと思うので、リストにして1つ1つ要素に数値や演算記号を追加していくことで、簡潔に書けるのではないかと思いました。

**Comment by c0a2109372** [comment]
演算キーを横に追加していくと考えた時、この形式の方が追加しやすかったため、今回はこの書き方となりました。
