### ISSUE TITLE
key2つありませんか？

### ISSUE THREAD

**Issue by MikamiSyota** [c0a2109372/ProjExD#6]
https://github.com/c0a2109372/ProjExD/blob/d6c895b6952c53ddcc0aabe2e1b1c6f90ba8fc5c/ex03/maze.py#L16
隠しコマンド機能などがあっていいと思いました。全体的にコードを読んでグローバル関数のところに、keyが2つあってなにか意図があるのかなとおもいました。

**Comment by c0a2109372** [comment]
不要でしたので削除させていただきました
