### ISSUE TITLE
空白行とコメント

### ISSUE THREAD

**Issue by MikamiSyota** [c0a2109372/ProjExD#9]
https://github.com/c0a2109372/ProjExD/blob/1752a03c0b9bd79b6b1e13d3501000706a41a8af/ex04/dodge_boomb.py#L39
コードをみてて、リストを用いたfor文の使い方、1秒という情報の取得方法など参考になったことがたくさんありました。
たまに、変に空白行がありますが、消したほうがよりよくなると思います。もし、意味のあった空白行ならコメントをするべきだと思います。

**Comment by c0a2109372** [comment]
修正しました
